#!/usr/bin/env bash

LOGIN_URL='https://net2.sharif.edu/login'

INFO_FILE='info'
FILE_PATH="$HOME/.local/bin/"

create_info_file() {
    echo "Enter your username:"
    read -r USERNAME
    echo -e "\033[32m""Don't worry, your pass is coming in, It won't be shown on the terminal just for security :)""\033[0m"
    echo "Enter your password:"
    read -r -s PASSWORD
    echo

    touch "${FILE_PATH}${INFO_FILE}"
    echo "$USERNAME" > "${FILE_PATH}${INFO_FILE}"
    echo "$PASSWORD" >> "${FILE_PATH}${INFO_FILE}"
    chmod 600 "${FILE_PATH}${INFO_FILE}"

    echo "Credentials saved to $INFO_FILE"
}

read_info_file() {
    USERNAME=$(sed -n '1p' "$1")
    PASSWORD=$(sed -n '2p' "$1")
}

remove_info_file() {
    if [ -f "${FILE_PATH}${INFO_FILE}" ]; then
        rm "${FILE_PATH}${INFO_FILE}"
        echo "credentials removed"
    else
        echo "No credentials found to remove."
    fi
}

login() {
    if [ -f "${FILE_PATH}${INFO_FILE}" ]; then
        read_info_file "${FILE_PATH}${INFO_FILE}"
    else
        echo "Enter your username:"
        read -r USERNAME
        echo -e "\033[32m""Don't worry, your pass is coming in, it won't be shown on the terminal just for security :)""\033[0m"
        echo "Enter your password:"
        read -r -s PASSWORD
        echo
    fi

    response=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$LOGIN_URL" \
      -d "USERNAME=$USERNAME" \
      -d "PASSWORD=$PASSWORD")

    if [ "$response" -ne 200 ]; then
        echo 'Natonestam Jenaab!'
        exit 1
    fi

    echo 'Login successful!'
}

case "$1" in
    install)

        if [ "$2" == "--help" ];then
            echo '
    Install the script to makes possible using it in any PATH

    Usage:
      sut_login install

    Flags:
      -h, --help   help for install

    Use "sut_login [command] --help" for more information about a command.
    '
        fi

        mkdir ~/.local/bin/ 2>/dev/null
        cp $1 "${FILE_PATH}/sut_login"
        chmod 700 "${FILE_PATH}/sut_login"
        echo 'export PATH="$PATH:/home/$USER/.local/bin"' >> "$HOME/."$(echo $SHELL | awk -F '/' '{print $NF}')"rc"
        ;;
    create_profile)

        if [ "$2" == "--help" ];then
            echo '
    Store your username and password to never ask again

    Usage:
      sut_login create_profile

    Flags:
      -h, --help   help for install

    Use "sut_login [command] --help" for more information about a command.
    '
        fi

        create_info_file
        ;;
    remove_profile)

        if [ "$2" == "--help" ];then
            echo '
    Remove the stored username and password file

    Usage:
      sut_login remove_profile

    Flags:
      -h, --help   help for install

    Use "sut_login [command] --help" for more information about a command.
    '
        fi

        remove_info_file
        ;;
    "")
        login
        ;;
    *)
        echo '
    This is a simple script that helps you to login easier :D

    Usage:
    sut_login [command]

    Available Commands:
      install           Install the script to makes possible using it in any PATH
      create_profile    Store your username and password to never ask again
      remove_profile    Remove the stored username and password file
      help              Help about any command

    Use "sut_login [command] --help" for more information about a command.
    '
        ;;
esac
